### ISSUE TITLE
Exception stops users from changing date range when dashboard contains datatable

### ISSUE THREAD

**Issue by ElijahGlover** [aalpern/tessera#14]
When changing the date range js throws an exception. PR to follow

`Uncaught TypeError: Cannot read property 'isDataTable' of undefined`

**Comment by ElijahGlover** [comment]
PR #15

**Comment by aalpern** [comment]
Confirmed fixed and merged. Thanks!

**Comment by ElijahGlover** [comment]
No Problem!
